### ISSUE TITLE
Does this project support ardupilot? 

### ISSUE THREAD

**Issue by hughhugh** [Jaeyoung-Lim/mavros_swarm#18]
Hi, 
I am using **Pixhawk 2.4.8** with firmware apmrover, it is compiled from ardupilot. This project is very good. I have installed mavros. Will ardupilot will be supported? Or , should I use px4 autopilot firmware? 
Thank you.

**Comment by Jaeyoung-Lim** [comment]
@hughhugh As it is communicating through mavros, it should be both supported, but as far as I know it was never tested with ardupilot. The behavior might vary depending on the autopilot

Though I am confused, are you trying to use this on a rover?

**Comment by hughhugh** [comment]
@Jaeyoung-Lim 
Hi, Lim.  I can run the mavros now to co-simulation with the rover firmware Rover-3.5.1. I am testing the connection between the pixhawk board and the mavros. I am planning to implement a path planning algorithm in ros, so I need to mavros to publish or send messages. Are there more examples on mavros? Thank you.

**Comment by Jaeyoung-Lim** [comment]
@hughhugh Are you using this repo? or is this a general question on mavros?

**Comment by hughhugh** [comment]
@Jaeyoung-Lim 
yes, it is a general question. Right now, I get more familiar with mavros, but if there are more examples, it would be better. Because if I connect to the pixhawk using apm.launch file, but i can NOT set some parameters or else one by one.

**Comment by Jaeyoung-Lim** [comment]
@hughhugh I have no experience with ardupilot
