### ISSUE TITLE
wstool init and merge

### ISSUE THREAD

**Issue by Wayne-xixi** [Jaeyoung-Lim/mavros_swarm#25]
Hello, I followed the readme instrutions and clone the package. And i used wstool `wstool init . ./mavros_swarm/dependencies.rosinstall` and i got this error: Error:There already is a workspace config file .rosinstall at ".". Use wstool install/modify.  So i changed the wstool merge `wstool merge . ./mavros_swarm/dependencies.rosinstall`  Then i got this error `Error: Too many arguments. wstool merge [URI] [OPTIONS]`

Could you help me to fix it?
Thank you!

**Comment by Jaeyoung-Lim** [comment]
If you want to do a merge, you can do `merge -t`

**Comment by Wayne-xixi** [comment]
And then I got this `wstool merge -t . ./mavros_swarm/dependencies.rosinstall 
Merge caused no change, no new elements found` I don’t know what's wrong with my steps?

**Comment by Jaeyoung-Lim** [comment]
@Wayne-xixi It means you already got everything you need with wstool merge

**Comment by Wayne-xixi** [comment]
> @Wayne-xixi It means you already got everything you need with wstool merge
But when I catkin build formation control I got this error `Errors     << formation_control:cmake /home/fapsros/catkin_ws/logs/formation_control/build.cmake.006.log
CMake Error at /home/fapsros/catkin_ws/devel/share/catkin_simple/cmake/catkin_simple-extras.cmake:38 (find_package):
  By not providing "Findgeodetic_utils.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "geodetic_utils", but CMake did not find one.

  Could not find a package configuration file provided by "geodetic_utils"
  with any of the following names:

    geodetic_utilsConfig.cmake
    geodetic_utils-config.cmake

  Add the installation prefix of "geodetic_utils" to CMAKE_PREFIX_PATH or set
  "geodetic_utils_DIR" to a directory containing one of the above files.  If
  "geodetic_utils" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:7 (catkin_simple)
` 
Before I got error to tell me to install catkin simple and eigen catkin. So I followed it, but it still didn’t work.

**Comment by Jaeyoung-Lim** [comment]
@Wayne-xixi You can get geodetic_utils from here: https://github.com/ethz-asl/geodetic_utils

**Comment by Wayne-xixi** [comment]
@Jaeyoung-Lim thanks! It works! I can run the .launch file `roslaunch formation_control sitl_multiuav_swarm.launch` And I can see three uavs in  gazebo. But they cant fly to 2 m. The result in the console like below:
`[ERROR] [1573815428.077148743, 6.000000000]: MODE: Unsupported FCU
[ INFO] [1573815428.078621696, 6.000000000]: Setting to Offboard
[ INFO] [1573815428.080062312, 6.004000000]: Setting to Offboard
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
[ INFO] [1573815433.775949897, 11.612000000]: HP: requesting home position
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
[ERROR] [1573815434.185476136, 12.000000000]: MODE: Unsupported FCU
[ INFO] [1573815434.187234041, 12.004000000]: Setting to Offboard
[ INFO] [1573815434.188780956, 12.004000000]: Setting to Offboard
[ WARN] [1573815434.191301877, 12.008000000]: CMD: Unexpected command 176, result 1
[ WARN] [1573815434.195280246, 12.012000000]: CMD: Unexpected command 176, result 1
[ INFO] [1573815434.840522424, 12.644000000]: HP: requesting home position
[ INFO] [1573815438.879485409, 16.612000000]: WP: item #0* F:2 C:178 p: 1.000000 5.000000 -1.000000 0.000000 x: 0.000000 y: 0.000000 z: 0.000000
[ INFO] [1573815438.879711835, 16.612000000]: WP: item #1  F:3 C: 22 p: 15.000000 0.000000 0.000000 nan x: 47.397705 y: 8.546729 z: 5.000000
[ INFO] [1573815438.879889092, 16.612000000]: WP: item #2  F:3 C: 16 p: 0.000000 0.000000 0.000000 nan x: 47.398804 y: 8.544907 z: 50.000000
[ INFO] [1573815438.880062298, 16.612000000]: WP: item #3  F:3 C: 16 p: 0.000000 0.000000 0.000000 nan x: 47.397778 y: 8.542441 z: 50.000000
[ INFO] [1573815438.880236273, 16.612000000]: WP: item #4  F:2 C: 20 p: 0.000000 0.000000 0.000000 0.000000 x: 0.000000 y: 0.000000 z: 0.000000
[ INFO] [1573815438.880360171, 16.612000000]: WP: mission received
[ INFO] [1573815439.935559998, 17.644000000]: WP: item #0* F:2 C:178 p: 1.000000 5.000000 -1.000000 0.000000 x: 0.000000 y: 0.000000 z: 0.000000
[ INFO] [1573815439.935938887, 17.644000000]: WP: item #1  F:3 C: 22 p: 15.000000 0.000000 0.000000 nan x: 47.397705 y: 8.546729 z: 5.000000
[ INFO] [1573815439.936269097, 17.644000000]: WP: item #2  F:3 C: 16 p: 0.000000 0.000000 0.000000 nan x: 47.398804 y: 8.544907 z: 50.000000
[ INFO] [1573815439.936606011, 17.644000000]: WP: item #3  F:3 C: 16 p: 0.000000 0.000000 0.000000 nan x: 47.397778 y: 8.542441 z: 50.000000
[ INFO] [1573815439.936921484, 17.644000000]: WP: item #4  F:2 C: 20 p: 0.000000 0.000000 0.000000 0.000000 x: 0.000000 y: 0.000000 z: 0.000000
[ INFO] [1573815439.937089173, 17.644000000]: WP: mission received
[ERROR] [1573815440.305010471, 18.000000000]: MODE: Unsupported FCU
[ INFO] [1573815440.306481957, 18.004000000]: Setting to Offboard
[ INFO] [1573815440.307864116, 18.004000000]: Setting to Offboard
[ERROR] [1573815446.399883918, 24.000000000]: MODE: Unsupported FCU
[ INFO] [1573815446.401100134, 24.000000000]: Setting to Offboard
[ INFO] [1573815446.402472865, 24.004000000]: Setting to Offboard
[ WARN] [1573815446.410362276, 24.012000000]: CMD: Unexpected command 176, result 1
[ WARN] [1573815446.410568727, 24.012000000]: CMD: Unexpected command 176, result 1
[ERROR] [1573815452.446849248, 30.000000000]: MODE: Unsupported FCU
[ INFO] [1573815452.448344201, 30.004000000]: Setting to Offboard
[ INFO] [1573815452.449943566, 30.004000000]: Setting to Offboard
[ERROR] [1573815458.551689117, 36.000000000]: MODE: Unsupported FCU
[ INFO] [1573815458.553385631, 36.000000000]: Setting to Offboard
[ INFO] [1573815458.555101352, 36.004000000]: Setting to Offboard
[ WARN] [1573815458.558208870, 36.008000000]: CMD: Unexpected command 176, result 1
[ WARN] [1573815458.567839564, 36.016000000]: CMD: Unexpected command 176, result 1
[ERROR] [1573815464.640697712, 42.000000000]: MODE: Unsupported FCU
[ INFO] [1573815464.642277243, 42.000000000]: Setting to Offboard
[ INFO] [1573815464.643935065, 42.004000000]: Setting to Offboard
[ERROR] [1573815470.720931588, 48.000000000]: MODE: Unsupported FCU
[ INFO] [1573815470.722514471, 48.000000000]: Setting to Offboard
[ WARN] [1573815470.724108599, 48.004000000]: CMD: Unexpected command 176, result 1
[ INFO] [1573815470.724762453, 48.004000000]: Setting to Offboard
[ WARN] [1573815470.732463781, 48.012000000]: CMD: Unexpected command 176, result 1
[ERROR] [1573815476.794223451, 54.000000000]: MODE: Unsupported FCU
[ INFO] [1573815476.795596181, 54.000000000]: Setting to Offboard
[ INFO] [1573815476.796866105, 54.004000000]: Setting to Offboard
[ERROR] [1573815482.868577599, 60.000000000]: MODE: Unsupported FCU
[ INFO] [1573815482.869880837, 60.000000000]: Setting to Offboard
[ WARN] [1573815482.873403632, 60.004000000]: CMD: Unexpected command 176, result 1
[ INFO] [1573815482.873556584, 60.004000000]: Setting to Offboard
[ WARN] [1573815482.879556369, 60.012000000]: CMD: Unexpected command 176, result 1
[ERROR] [1573815488.946480313, 66.000000000]: MODE: Unsupported FCU
[ INFO] [1573815488.948493139, 66.004000000]: Setting to Offboard
[ INFO] [1573815488.950309012, 66.004000000]: Setting to Offboard
[ERROR] [1573815495.022773953, 72.000000000]: MODE: Unsupported FCU
[ INFO] [1573815495.023886106, 72.000000000]: Setting to Offboard
[ INFO] [1573815495.024993020, 72.004000000]: Setting to Offboard
[ WARN] [1573815495.033209708, 72.012000000]: CMD: Unexpected command 176, result 1
[ WARN] [1573815495.033499828, 72.012000000]: CMD: Unexpected command 176, result 1
[ERROR] [1573815501.089543687, 78.000000000]: MODE: Unsupported FCU
[ INFO] [1573815501.091818837, 78.004000000]: Setting to Offboard
[ INFO] [1573815501.093540844, 78.004000000]: Setting to Offboard
[ERROR] [1573815507.182310582, 84.000000000]: MODE: Unsupported FCU
[ INFO] [1573815507.184225839, 84.000000000]: Setting to Offboard
[ INFO] [1573815507.186152970, 84.004000000]: Setting to Offboard
[ WARN] [1573815507.192278469, 84.012000000]: CMD: Unexpected command 176, result 1
[ WARN] [1573815507.200717531, 84.020000000]: CMD: Unexpected command 176, result 1
[ERROR] [1573815513.257569524, 90.000000000]: MODE: Unsupported FCU
[ INFO] [1573815513.259029346, 90.000000000]: Setting to Offboard
[ INFO] [1573815513.260410877, 90.004000000]: Setting to Offboard
[ERROR] [1573815519.312002493, 96.000000000]: MODE: Unsupported FCU
[ INFO] [1573815519.313356576, 96.000000000]: Setting to Offboard
[ INFO] [1573815519.314502672, 96.004000000]: Setting to Offboard
[ WARN] [1573815519.318461555, 96.008000000]: CMD: Unexpected command 176, result 1
[ WARN] [1573815519.318644539, 96.008000000]: CMD: Unexpected command 176, result 1
`
Unsupported FCU means I have unsupported versions or I just made wrong settings?

**Comment by Jaeyoung-Lim** [comment]
May be you have the wrong firmware version or the firmware has not been build properly.

Can you run PX4 SITL properly? How were you running it?

**Comment by Wayne-xixi** [comment]
@Jaeyoung-Lim yes, I can run it, and I can control the uav to fly and land.

**Comment by Jaeyoung-Lim** [comment]
@Wayne-xixi Please share the full log of your output. I suspect that you are not able to run SITL properly

**Comment by Wayne-xixi** [comment]
@Jaeyoung-Lim ok, like below.
`make px4_sitl_default gazebo[2/6] Performing configure step for 'sitl_gazebo'
-- install-prefix: /usr/local
-- Using C++14 compiler
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Boost version: 1.58.0
-- Building klt_feature_tracker without catkin
-- Building OpticalFlow with OpenCV
-- catkin DISABLED
Gazebo version: 7.16
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fapsros/Firmware/build/px4_sitl_default/build_gazebo
[3/6] Performing build step for 'sitl_gazebo'
ninja: no work to do.
[6/6] cd /home/fapsros/Firmware/build/...apsros/Firmware/build/px4_sitl_default
SITL ARGS
sitl_bin: /home/fapsros/Firmware/build/px4_sitl_default/bin/px4
debugger: none
program: gazebo
model: none
src_path: /home/fapsros/Firmware
build_path: /home/fapsros/Firmware/build/px4_sitl_default
empty model, setting iris as default
GAZEBO_PLUGIN_PATH :/home/fapsros/Documents/gazebo_plugin_tutorial/build/:/home/fapsros/Firmware/build/px4_sitl_default/build_gazebo:/home/fapsros/Firmware/build/posix_sitl_default/build_gazebo:/home/fapsros/Firmware/build/px4_sitl_default/build_gazebo:/home/fapsros/Firmware/build/px4_sitl_default/build_gazebo
GAZEBO_MODEL_PATH :/home/fapsros/Firmware/Tools/sitl_gazebo/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/worlds:/home/fapsros/Firmware/Tools/sitl_gazebo/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/worlds:/home/fapsros/Firmware/Tools/sitl_gazebo/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/worlds:/home/fapsros/Firmware/Tools/sitl_gazebo/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/worlds:/home/fapsros/Firmware/Tools/sitl_gazebo/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/worlds:/home/fapsros/Firmware/Tools/sitl_gazebo/models:/home/fapsros/Firmware/Tools/sitl_gazebo/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/worlds:/home/fapsros/Firmware/Tools/sitl_gazebo/models:/home/fapsros/Firmware/Tools/sitl_gazebo/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/models:/home/fapsros/catkin_ws/src/avoidance/avoidance/sim/worlds:/home/fapsros/Firmware/Tools/sitl_gazebo/models:/home/fapsros/catkin_ws/src/realsense_gazebo_plugin/models:/home/fapsros/Firmware/Tools/sitl_gazebo/models:/home/fapsros/Firmware/Tools/sitl_gazebo/models:/home/fapsros/Firmware/Tools/sitl_gazebo/models
LD_LIBRARY_PATH /home/fapsros/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/fapsros/Firmware/build/px4_sitl_default/build_gazebo:/home/fapsros/Firmware/build/posix_sitl_default/build_gazebo:/home/fapsros/Firmware/build/px4_sitl_default/build_gazebo:/home/fapsros/Firmware/build/px4_sitl_default/build_gazebo
Gazebo multi-robot simulator, version 7.16.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.113.18
[Wrn] [gazebo_barometer_plugin.cpp:66] [gazebo_barometer_plugin] Using default home altitude of 488 m
[Dbg] [gazebo_mavlink_interface.cpp:135] <joint_name> not found for channel[0] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:135] <joint_name> not found for channel[1] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:135] <joint_name> not found for channel[2] no joint control will be performed for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:135] <joint_name> not found for channel[3] no joint control will be performed for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:124] joint [zephyr_delta_wing::propeller_joint] not found for channel[4] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:124] joint [zephyr_delta_wing::flap_left_joint] not found for channel[5] no joint control for this channel.
[Wrn] [gazebo_mavlink_interface.cpp:124] joint [zephyr_delta_wing::flap_right_joint] not found for channel[6] no joint control for this channel.
[Dbg] [gazebo_mavlink_interface.cpp:135] <joint_name> not found for channel[7] no joint control will be performed for this channel.
[Msg] Connecting to PX4 SITL using TCP
[Msg] Lockstep is enabled
[Msg] Speed factor set to: 1
SITL COMMAND: "/home/fapsros/Firmware/build/px4_sitl_default/bin/px4" "/home/fapsros/Firmware"/ROMFS/px4fmu_common -s etc/init.d-posix/rcS -t "/home/fapsros/Firmware"/test_data
INFO  [px4] Creating symlink /home/fapsros/Firmware/ROMFS/px4fmu_common -> /home/fapsros/Firmware/build/px4_sitl_default/tmp/rootfs/etc
0 WARNING: setRealtimeSched failed (not run as root?)

______  __   __    ___ 
| ___ \ \ \ / /   /   |
| |_/ /  \ V /   / /| |
|  __/   /   \  / /_| |
| |     / /^\ \ \___  |
\_|     \/   \/     |_/

px4 starting.

INFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
INFO  [dataman] Unknown restart, data manager file './dataman' size is 11798680 bytes
INFO  [simulator] Waiting for simulator to connect on TCP port 4560
INFO  [simulator] Simulator connected on TCP port 4560.
[Msg] Using MAVLink protocol v2.0
Gazebo multi-robot simulator, version 7.16.0
Copyright (C) 2012 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

[Msg] Waiting for master.
[Msg] Connected to gazebo master @ http://127.0.0.1:11345
[Msg] Publicized address: 192.168.113.18
INFO  [init] Mixer: etc/mixers/quad_w.main.mix on /dev/pwm_output0
INFO  [mavlink] mode: Normal, data rate: 4000000 B/s on udp port 14570 remote port 14550
INFO  [mavlink] mode: Onboard, data rate: 4000000 B/s on udp port 14580 remote port 14540
INFO  [logger] logger started (mode=all)
INFO  [logger] Start file log (type: full)
INFO  [logger] Opened full log file: ./log/2019-11-15/14_14_56.ulg
INFO  [mavlink] MAVLink only on localhost (set param MAV_BROADCAST = 1 to enable network)
INFO  [px4] Startup script returned successfully
pxh> [Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris/motors, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris/motor_speed/0, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris/motor_speed/1, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris/motor_speed/2, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:141] Queue limit reached for topic /gazebo/default/iris/motor_speed/3, deleting message. This warning is printed only once.
INFO  [ecl/EKF] EKF aligned, (pressure height, IMU buf: 22, OBS buf: 14)
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
`

**Comment by Jaeyoung-Lim** [comment]
Not sure. Do you get mavlink from all three vehicles? It seems like there is only one SITL instance starting

**Comment by Wayne-xixi** [comment]
ok, thank you, I try to fix it.

**Comment by Jaeyoung-Lim** [comment]
@Wayne-xixi Actually, the second log you have posted are not from launching the launchfile, but you are running `make px4_sitl_gazebo default`. That would only launch one vehicle. Is this the outcome you are aiming for?

**Comment by Jaeyoung-Lim** [comment]
@Wayne-xixi any updates?

**Comment by Wayne-xixi** [comment]
@Jaeyoung-Lim hello Jaeyoung, sorry for the late reply. I had just roslaunch formation_control. And I still met the same problem. I can see the three drones in gazebo, but not to off load and take off to 2 m. The console is below. Please see the error ist unsupported FCU. Thank you.
```
[ INFO] [1574172713.551307367, 5.936000000]: VER: 3.1: Board hardware:      00000001
[ INFO] [1574172713.551343684, 5.936000000]: VER: 3.1: VID/PID:             0000:0000
[ INFO] [1574172713.551379862, 5.936000000]: VER: 3.1: UID:                 4954414c44494e51
[ERROR] [1574172713.616550440, 6.000000000]: MODE: Unsupported FCU
[ INFO] [1574172713.618836904, 6.004000000]: Setting to Offboard
[ INFO] [1574172713.620773533, 6.004000000]: Setting to Offboard
[ERROR] [1574172719.733157307, 12.000000000]: MODE: Unsupported FCU
[ INFO] [1574172719.734766800, 12.000000000]: Setting to Offboard
[ INFO] [1574172719.736418756, 12.004000000]: Setting to Offboard
[ WARN] [1574172719.739376464, 12.008000000]: CMD: Unexpected command 176, result 1
[ WARN] [1574172719.752630734, 12.020000000]: CMD: Unexpected command 176, result 1
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
INFO  [ecl/EKF] EKF GPS checks passed (WGS-84 origin set)
INFO  [ecl/EKF] EKF commencing GPS fusion
[ INFO] [1574172722.754687490, 14.936000000]: HP: requesting home position
[ERROR] [1574172725.889395262, 18.000000000]: MODE: Unsupported FCU
[ INFO] [1574172725.891604412, 18.004000000]: Setting to Offboard
[ INFO] [1574172725.893095174, 18.004000000]: Setting to Offboard
[ INFO] [1574172727.240498919, 19.328000000]: WP: item #0* F:2 C:178 p: 1.000000 5.000000 -1.000000 0.000000 x: 0.000000 y: 0.000000 z: 0.000000
[ INFO] [1574172727.240698385, 19.328000000]: WP: item #1  F:3 C: 22 p: 15.000000 0.000000 0.000000 nan x: 47.397705 y: 8.546729 z: 5.000000
[ INFO] [1574172727.240877738, 19.328000000]: WP: item #2  F:3 C: 16 p: 0.000000 0.000000 0.000000 nan x: 47.398804 y: 8.544907 z: 50.000000
[ INFO] [1574172727.241038792, 19.328000000]: WP: item #3  F:3 C: 16 p: 0.000000 0.000000 0.000000 nan x: 47.397778 y: 8.542441 z: 50.000000
[ INFO] [1574172727.241176100, 19.328000000]: WP: item #4  F:2 C: 20 p: 0.000000 0.000000 0.000000 0.000000 x: 0.000000 y: 0.000000 z: 0.000000
[ INFO] [1574172727.241253414, 19.328000000]: WP: mission received
[ INFO] [1574172727.865257207, 19.936000000]: WP: item #0* F:2 C:178 p: 1.000000 5.000000 -1.000000 0.000000 x: 0.000000 y: 0.000000 z: 0.000000
[ INFO] [1574172727.865488800, 19.936000000]: WP: item #1  F:3 C: 22 p: 15.000000 0.000000 0.000000 nan x: 47.397705 y: 8.546729 z: 5.000000
[ INFO] [1574172727.865661658, 19.936000000]: WP: item #2  F:3 C: 16 p: 0.000000 0.000000 0.000000 nan x: 47.398804 y: 8.544907 z: 50.000000
[ INFO] [1574172727.865824108, 19.936000000]: WP: item #3  F:3 C: 16 p: 0.000000 0.000000 0.000000 nan x: 47.397778 y: 8.542441 z: 50.000000
[ INFO] [1574172727.865990121, 19.936000000]: WP: item #4  F:2 C: 20 p: 0.000000 0.000000 0.000000 0.000000 x: 0.000000 y: 0.000000 z: 0.000000
[ INFO] [1574172727.866073372, 19.936000000]: WP: mission received
[ERROR] [1574172732.020664399, 24.004000000]: MODE: Unsupported FCU
[ INFO] [1574172732.022558146, 24.008000000]: Setting to Offboard
[ INFO] [1574172732.024183143, 24.008000000]: Setting to Offboard
[ WARN] [1574172732.033572116, 24.020000000]: CMD: Unexpected command 176, result 1
[ WARN] [1574172732.033963507, 24.020000000]: CMD: Unexpected command 176, result 1
[ERROR] [1574172738.134785616, 30.000000000]: MODE: Unsupported FCU
[ INFO] [1574172738.136377787, 30.000000000]: Setting to Offboard
[ INFO] [1574172738.139064162, 30.004000000]: Setting to Offboard
[ERROR] [1574172744.306227459, 36.000000000]: MODE: Unsupported FCU
[ INFO] [1574172744.308335548, 36.004000000]: Setting to Offboard
[ INFO] [1574172744.309724203, 36.004000000]: Setting to Offboard
[ WARN] [1574172744.315069785, 36.012000000]: CMD: Unexpected command 176, result 1
[ WARN] [1574172744.318692312, 36.016000000]: CMD: Unexpected command 176, result 1
[ERROR] [1574172750.424044466, 42.000000000]: MODE: Unsupported FCU
[ INFO] [1574172750.425602765, 42.004000000]: Setting to Offboard
[ INFO] [1574172750.427261496, 42.004000000]: Setting to Offboard
[ERROR] [1574172756.561030811, 48.000000000]: MODE: Unsupported FCU
[ INFO] [1574172756.562810716, 48.004000000]: Setting to Offboard
[ WARN] [1574172756.563334805, 48.004000000]: CMD: Unexpected command 176, result 1
[ INFO] [1574172756.565291339, 48.004000000]: Setting to Offboard
[ WARN] [1574172756.572777766, 48.012000000]: CMD: Unexpected command 176, result 1
[ERROR] [1574172762.700785734, 54.000000000]: MODE: Unsupported FCU
[ INFO] [1574172762.702183677, 54.004000000]: Setting to Offboard
[ INFO] [1574172762.703409741, 54.004000000]: Setting to Offboard
[ERROR] [1574172768.820045243, 60.000000000]: MODE: Unsupported FCU
[ INFO] [1574172768.821398418, 60.000000000]: Setting to Offboard
[ WARN] [1574172768.822245383, 60.004000000]: CMD: Unexpected command 176, result 1
[ INFO] [1574172768.823232241, 60.004000000]: Setting to Offboard
[ WARN] [1574172768.830366039, 60.012000000]: CMD: Unexpected command 176, result 1
[ERROR] [1574172774.967022244, 66.000000000]: MODE: Unsupported FCU
[ INFO] [1574172774.968760943, 66.004000000]: Setting to Offboard
[ INFO] [1574172774.970188848, 66.004000000]: Setting to Offboard
[ERROR] [1574172781.109528774, 72.000000000]: MODE: Unsupported FCU
[ INFO] [1574172781.111526234, 72.004000000]: Setting to Offboard
[ WARN] [1574172781.112949670, 72.004000000]: CMD: Unexpected command 176, result 1
[ INFO] [1574172781.117257480, 72.004000000]: Setting to Offboard
[ WARN] [1574172781.126830834, 72.016000000]: CMD: Unexpected command 176, result 1
[ERROR] [1574172787.260705750, 78.000000000]: MODE: Unsupported FCU
[ INFO] [1574172787.265330011, 78.000000000]: Setting to Offboard
[ INFO] [1574172787.267361764, 78.004000000]: Setting to Offboard
[ERROR] [1574172793.479196872, 84.000000000]: MODE: Unsupported FCU
[ WARN] [1574172793.482079781, 84.000000000]: CMD: Unexpected command 176, result 1
[ INFO] [1574172793.482235946, 84.000000000]: Setting to Offboard
[ INFO] [1574172793.484862327, 84.004000000]: Setting to Offboard
[ WARN] [1574172793.486894080, 84.008000000]: CMD: Unexpected command 176, result 1
[ERROR] [1574172799.669452002, 90.000000000]: MODE: Unsupported FCU
[ INFO] [1574172799.671202504, 90.000000000]: Setting to Offboard
[ INFO] [1574172799.672624263, 90.000000000]: Setting to Offboard
[ERROR] [1574172805.838140283, 96.004000000]: MODE: Unsupported FCU
[ INFO] [1574172805.839887921, 96.004000000]: Setting to Offboard
[ INFO] [1574172805.841261420, 96.004000000]: Setting to Offboard
[ WARN] [1574172805.846671116, 96.008000000]: CMD: Unexpected command 176, result 1
[ WARN] [1574172805.851077682, 96.008000000]: CMD: Unexpected command 176, result 1
[ERROR] [1574172811.954936700, 102.000000000]: MODE: Unsupported FCU
[ INFO] [1574172811.956455049, 102.000000000]: Setting to Offboard
[ INFO] [1574172811.957686491, 102.000000000]: Setting to Offboard
```

**Comment by Wayne-xixi** [comment]
![Screenshot from 2019-11-19 15-25-14](https://user-images.githubusercontent.com/56882488/69154858-12f22580-0ae1-11ea-9c36-0a55e64046b2.png)

**Comment by Wayne-xixi** [comment]
@Jaeyoung-Lim This is my screen shot

**Comment by Jaeyoung-Lim** [comment]
@Wayne-xixi You might have not set your environment properly see: https://github.com/PX4/Firmware/issues/12038

**Comment by Wayne-xixi** [comment]
@Jaeyoung-Lim Hello, update! Today when I roslaunch, i got this error.
```
px4 starting.
NFO  [px4] Calling startup script: /bin/sh etc/init.d-posix/rcS 0
Error: Unknown model ''
ERROR [px4] Startup script returned with return value: 256
```

I have checked the launch file: <include file="$(find px4)/launch/single_vehicle_spawn.launch"> 

So I cant open the models. Do you know the reason?

Thank you!

**Comment by Jaeyoung-Lim** [comment]
Did you set the environment variables properly?

**Comment by Wayne-xixi** [comment]
@Jaeyoung-Lim Yes, I follow your instructions.  cd src/Firmware 
source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/px4_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)/Tools/sitl_gazebo

**Comment by Wayne-xixi** [comment]
@Jaeyoung-Lim And 
roslaunch px4 mavros_posix_sitl.launch was ok.

**Comment by Jaeyoung-Lim** [comment]
@Wayne-xixi And did you run
```
make px4_sitl_default gazebo
```
before you run the simulation? This is to build the firmware

**Comment by Wayne-xixi** [comment]
@Jaeyoung-Lim Yes make px4_sitl_default gazebo was also ok.

**Comment by rhamrah** [comment]
@Wayne-xixi Did you fix this issue? 
@Jaeyoung-Lim I have the same issue. roslaunch formation_control sitl_multiuav_swarm.launch runs the gazebo with 3 drones but not arming and hovering. QGC shows "Not ready to fly" and does not even fly them manually.
