### ISSUE TITLE
catkin build formation_control Not working

### ISSUE THREAD

**Issue by ebasatemesgen** [Jaeyoung-Lim/mavros_swarm#27]
I keep getting this error when I try to catkin build..

``build] Found '9' packages in 0.0 seconds.                                     
[build] Updating package table.                                                
Starting  >>> catkin_tools_prebuild                                            
Finished  <<< catkin_tools_prebuild                [ 7.3 seconds ]             
Starting  >>> catkin_simple                                                    
Finished  <<< catkin_simple                        [ 3.1 seconds ]             
Starting  >>> eigen_catkin                                                     
Finished  <<< eigen_catkin                         [ 3.2 seconds ]             
Starting  >>> formation_control                                                
_______________________________________________________________________________
Errors     << formation_control:cmake /home/eeex/Eba_ws/logs/formation_control/build.cmake.000.log
CMake Error at /home/eeex/Eba_ws/devel/share/catkin_simple/cmake/catkin_simple-extras.cmake:38 (find_package):
  By not providing "Findmavros_msgs.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "mavros_msgs", but CMake did not find one.

  Could not find a package configuration file provided by "mavros_msgs" with
  any of the following names:

    mavros_msgsConfig.cmake
    mavros_msgs-config.cmake

  Add the installation prefix of "mavros_msgs" to CMAKE_PREFIX_PATH or set
  "mavros_msgs_DIR" to a directory containing one of the above files.  If
  "mavros_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:7 (catkin_simple)

**Comment by Jaeyoung-Lim** [comment]
@ebagirma Did you did the `wstool update` as written in the readme? It seems like you are missing mavros in your workspace

**Comment by Jaeyoung-Lim** [comment]
@ebagirma Ah, sorry please clone mavros into your workspace : [mavros](https://github.com/mavlink/mavros)

I will make a fix to have mavros included in the dependencies.rosinstall. Sorry that I missed that.

**Comment by Jaeyoung-Lim** [comment]
@ebagirma I have updated the dependencies.rosinstall too. It should be working now
