### ISSUE TITLE
Problem about running roslaunch formation_control sitl_multiuav_swarm.launch

### ISSUE THREAD

**Issue by AshleyHutcherson** [Jaeyoung-Lim/mavros_swarm#32]
i have problem on running `roslaunch formation_control sitl_multiuav_swarm.launch`
i've done sourcing but still can't run this

this is what it shows:
... logging to /home/ashley/.ros/log/4bc3c1c0-7a26-11ea-aaa4-a402b9cd65c2/roslaunch-ashley-UX305CA-2500.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Resource not found: px4
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/ashley/catkin_ws/src
ROS path [2]=/opt/ros/melodic/share
The traceback for the exception was written to the log file

**Comment by Jaeyoung-Lim** [comment]
@AshleyHutcherson You can set the path to px4 following the instructions [here](http://dev.px4.io/master/en/simulation/ros_interface.html#launching-gazebo-with-ros-wrappers)
