### ISSUE TITLE
WARN  [mavlink] SET_POSITION_TARGET_GLOBAL_INT invalid coordinate frame 0

### ISSUE THREAD

**Issue by GunhyukLee** [Jaeyoung-Lim/mavros_swarm#34]
Hi 

l have a obstacle in the process of marvros_swarm.                (Ubuntu 18.04, ROS-Melodic)

First of all, l added paths to ~/.bashrc as follows:

-----------------------------------------------------------------------------------------------------------------------------------------------------
source /opt/ros/melodic/setup.bash
source ~/catkin_ws/devel/setup.bash
source ~/PX4-Autopilot/Tools/setup_gazebo.bash ~/PX4-Autopilot ~/PX4-Autopilot/build/px4_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/PX4-Autopilot
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:~/PX4-Autopilot/Tools/sitl_gazebo
export GAZEBO_PLUGIN_PATH=$GAZEBO_PLUGIN_PATH:/usr/lib/x86_64-linux-gnu/gazebo-9/plugins
------------------------------------------------------------------------------------------------------------------------------------------------------

After that, I typed it in the terminal.
---------------------------------------------------------------------------------------------------------
cd ~/catkin_ws
wstool init src
wstool merge -t src src/mavros_swarm/dependencies.rosinstall
wstool update -t src -j4
catkin build formation_control
roslaunch formation_control sitl_multiuav_swarm.launch
-------------------------------------------------------------------------------------------------------

It was possible to check that three drones are on the Gazebo program when running, but the warning kept popping up.

> WARN  [mavlink] SET_POSITION_TARGET_GLOBAL_INT invalid coordinate frame 0
> WARN  [mavlink] SET_POSITION_TARGET_GLOBAL_INT invalid coordinate frame 0
> WARN  [mavlink] SET_POSITION_TARGET_GLOBAL_INT invalid coordinate frame 0
> WARN  [mavlink] SET_POSITION_TARGET_GLOBAL_INT invalid coordinate frame 0
> WARN  [mavlink] SET_POSITION_TARGET_GLOBAL_INT invalid coordinate frame 0

l think.. i need to modify the coordinate settings in PX4-Autopilot..?

I don’t know what I should do.  I need your help.

**Comment by Jaeyoung-Lim** [comment]
@GunhyukLee I think you have a incompatible mavros version with the firmware.

**Comment by GunhyukLee** [comment]
Does it mean that I should use this firmware version instead of the lastest version?

https://github.com/Jaeyoung-Lim/Firmware

**Comment by Jaeyoung-Lim** [comment]
@GunhyukLee No, your mavros is using a old mavlink version than what is used in the PX4 Firmware. What is the version of your mavros and the version of PX4?

**Comment by GunhyukLee** [comment]
PX4 :
> git clone https://github.com/PX4/PX4-Autopilot.git --recursive

l had a wrong version of marvros. (ros-kinetic-mavros)

I reinstalled (ros-melodic-mavros), but the results are same.

> WARN [mavlink] SET_POSITION_TARGET_GLOBAL_INT invalid coordinate frame 0
> WARN [mavlink] SET_POSITION_TARGET_GLOBAL_INT invalid coordinate frame 0
> WARN [mavlink] SET_POSITION_TARGET_GLOBAL_INT invalid coordinate frame 0

**Comment by Jaeyoung-Lim** [comment]
@GunhyukLee You should not use the binary package `ros-melodic-mavros` but build mavros from source and update the mavlink package to the latest version.

`ros-melodic-mavros` updates it's mavlink everymonth, while mavlink inside PX4 is continuously updating mavlink. Therefore you need to use a newer mavlink than what is packaged inside `ros-melodic-mavros`
