### ISSUE TITLE
Resource not found: px4

### ISSUE THREAD

**Issue by kc52** [Jaeyoung-Lim/mavros_swarm#35]
![WhatsApp Image 2022-04-25 at 00 53 13](https://user-images.githubusercontent.com/58978588/165153752-e5a6f4d0-f4bf-483f-8df8-8dbccdab691e.jpeg)
Hi Jaeyoung Lim,
I m getting this error as ' Resouce not found: px4' and its path. Could you pls help me How I can fix this error and be able to launch the simulation properly? I m using ubuntu 18.04 and ROS melodic version.

**Comment by Jaeyoung-Lim** [comment]
@kc52 As written in the log, it means that it means that px4 cannot be found in the package path.

Are you sure that you have followed the instruction in https://docs.px4.io/master/en/simulation/ros_interface.html to add px4 to the ROS path?

e.g.
```
cd <PX4-Autopilot_clone>
DONT_RUN=1 make px4_sitl_default gazebo
source ~/catkin_ws/devel/setup.bash    # (optional)
source Tools/setup_gazebo.bash $(pwd) $(pwd)/build/px4_sitl_default
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$(pwd)/Tools/sitl_gazebo
roslaunch px4 posix_sitl.launch
```
