### ISSUE TITLE
ERROR [simulator_mavlink] poll timeout 0, 22

### ISSUE THREAD

**Issue by tomsonlee13** [Jaeyoung-Lim/mavros_swarm#36]
Hi

I am trying to run the swarm sim but I have the following error and warnings: 

[ INFO] [1690323780.799220870, 6.004000000]: Setting to Offboard
WARN  [mavlink] SET_POSITION_TARGET_GLOBAL_INT invalid coordinate frame 0	
WARN  [mavlink] SET_POSITION_TARGET_GLOBAL_INT invalid coordinate frame 0	
WARN  [mavlink] SET_POSITION_TARGET_GLOBAL_INT invalid coordinate frame 0	
ERROR [simulator_mavlink] poll timeout 0, 22
ERROR [simulator_mavlink] poll timeout 0, 22
ERROR [simulator_mavlink] poll timeout 0, 22
poll timeout
![Screenshot from 2023-07-25 17-34-29](https://github.com/Jaeyoung-Lim/mavros_swarm/assets/71269722/1acb29cb-3b5c-42ed-a8bd-468123880b97)

Gazebo does show up but the three drones does not take off. It shows a lot of warnings on invalid coordinate frame 0. After setting the mode to Offboard, it starts to have errors of poll timeout. I pull the latest repo from PX4 as well as mavlink/mavros and compile from source. I am not sure what the problem is here.

**Comment by tomsonlee13** [comment]
The issue seems to be that the mavlink_receiver of PX4 latest version does not support target_global_int.coordinate_frame with the value "0". Work around is to modify one of the if branch as 0 but position might be inaccurate.

**Comment by tomsonlee13** [comment]
The issue seems to be that the mavlink_receiver of PX4 latest version does not support target_global_int.coordinate_frame with the value "0". Work around is to modify one of the if branch as 0 but position might be inaccurate.

**Comment by Jaeyoung-Lim** [comment]
@tomsonlee13 Thanks for the update. Would you be able to make a PR for the fix?

**Comment by tomsonlee13** [comment]
@Jaeyoung-Lim The workaround is to modify the mavlink_receiver.cpp on the PX4 end. We can't do a fix on here.

**Comment by Jaeyoung-Lim** [comment]
@tomsonlee13 You can also specify the coordinate frame when sending the reference
